---
language: generic

matrix:
  include:
    - os: linux
    - os: osx

env:
  global:
    - PACKAGE_NAME=zeroc-ice
    - PATH="$HOME/miniconda/bin:$PATH"

install:
  # xcode image is missing headers
  # https://github.com/travis-ci/travis-ci/issues/9640
  # https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#macos-sdk
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      pushd /opt;
      curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz | sudo tar xf -;
      popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda install -y conda-build anaconda-client
  - conda info -a

script:
  - conda build .

deploy:
  - provider: script
    skip_cleanup: true
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER -l nightly $HOME/miniconda/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE_NAME-*.tar.bz2 --force
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER $HOME/miniconda/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE_NAME-*.tar.bz2
    on:
      tags: true
